name: OTA Update

on:
  push:
    branches: [master, staging]

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Determine branch and create update
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "Deploying to production channel"
            eas update --branch production --message "Production update from master"
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "Deploying to staging channel"
            eas update --branch staging --message "Staging update"
          else
            echo "Deploying to development channel"
            eas update --branch development --message "Development update"
          fi
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}