name: OTA Update

on:
  push:
    branches: [main, master]

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Create update
        run: eas update --auto --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}